name = "double_pendulum_fractal"
version = "0.1.0"
license = "license"
author = "jjordanoc"
maintainer = "joaquin.jordan@utec.edu.pe"
copyright = "Copyright 2024, jjordanoc"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
fplot = { git = "https://github.com/jchristopherson/fplot" }
forcolormap = {git = "https://github.com/vmagnin/forcolormap.git" }

